# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 758e1fcdb04196060d45d6e0dedb2ba88339a9a982b9ed64e95e323d0417884afea41707a1b85cb661fce4fe553324900320fbd3921a2e4bbefcb02a99018fc4

test:
  secret_key_base: 9a57f5321656f695cd1b6746aa5d5f70d9986cf7a14fda72d982bdbe1ecbcc4794fd19358667ff366cff80aab46ea574bd6a0e7e79b207403f5f5d2d9b1a1068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
